import { runTankTemperatureForecastUnitTests } from "../lib/tankTemperatureForecast.test";
import { runInletTemperatureUnitTests } from "../lib/inletTemperature.test";
import { runHeatingHistoryUnitTests } from "../lib/heatingHistory.test";
import { runHeatingOptimizerUnitTests } from "../lib/heatingOptimizer.test";
import { runHeatingOptimizationRunUnitTests } from "../lib/heatingOptimizationRun.test";
import { runHeatingGainUnitTests } from "../lib/heatingGain.test";
import { runHeatingGainBacktestUnitTests } from "../lib/heatingGainBacktest.test";
import { runHeatingRecoveryDropUnitTests } from "../lib/heatingRecoveryDrop.test";
import { runRecoveryDropEnvironmentUnitTests } from "../lib/recoveryDropEnvironment.test";
import { runTemperatureDropProfileUnitTests } from "../lib/temperatureDropProfile.test";
import { runColorMixingUnitTests } from "../lib/colorMixing.test";
import { runTemperatureColorsUnitTests } from "../lib/temperatureColors.test";
import { runTemperaturePresentationUnitTests } from "../lib/temperaturePresentation.test";
import { runPricePresentationUnitTests } from "../lib/pricePresentation.test";
import { runPriceUtilsUnitTests } from "../lib/priceUtils.test";
import { runShowerReserveSettingsUnitTests } from "../lib/showerReserveSettings.test";
import { runHeatingSettingsUnitTests } from "../lib/heatingSettings.test";
import { runSettingsSectionSummaryUnitTests } from "../lib/settingsSectionSummaries.test";
import { runHeatingPlanPresentationUnitTests } from "../lib/heatingPlanPresentation.test";
import { runHeatingPlanPublicationUnitTests } from "../lib/heatingPlanPublication.test";
import { runHeatingEnergyCostUnitTests } from "../lib/heatingEnergyCost.test";
import { runElectricityPricesUnitTests } from "../lib/electricityPrices.test";
import { runHistoryUiSourceTests } from "../tests/historyUiSource.test";
import { runHeatingGainHistorySourceTests } from "../tests/heatingGainHistorySource.test";
import { runHeatingPlanMarkerUnitTests } from "../lib/heatingPlanMarkers.test";
import { runElectricityPriceTrendUnitTests } from "../lib/electricityPriceTrend.test";
import { runElectricityPriceFunctionUnitTests } from "../supabase/functions/fetch-electricity-prices/normalize.test";
import { runTemperatureHistoryDayUnitTests } from "../lib/temperatureHistoryDay.test";
import { runTemperatureHistoryRpcMigrationTests } from "../tests/temperatureHistoryRpcMigration.test";
import { runGetHeatingPeriodsRpcMigrationTests } from "../tests/getHeatingPeriodsRpcMigration.test";
import { runRecalculateTemperatureDropProfileRpcMigrationTests } from "../tests/recalculateTemperatureDropProfileRpcMigration.test";
import { runSettingsDraftUnitTests } from "../lib/settingsDraft.test";
import { runSettingsScenarioUnitTests } from "../lib/settingsScenario.test";
import { runSettingsDraftUiSourceTests } from "../tests/settingsDraftUiSource.test";
import { runSettingsScenarioUiSourceTests } from "../tests/settingsScenarioUiSource.test";
import { runHeatingOptimizationStatusSourceTests } from "../tests/heatingOptimizationStatusSource.test";
import { runTankMonitorAlertUnitTests } from "../lib/tankMonitorAlert.test";
import { runTankMonitorAlertLogicUnitTests } from "../supabase/functions/check-tank-monitor-health/alertLogic.test";
import { runInletTemperatureTrendUnitTests } from "../lib/inletTemperatureTrend.test";
import { runWaterDrawDetectionUnitTests } from "../lib/waterDrawDetection.test";
import { runTankReadingFreshnessUnitTests } from "../lib/tankReadingFreshness.test";
import { runSensorGeometryUnitTests } from "../lib/energyModelV2/sensorGeometry.test";
import { runReplayEngineUnitTests } from "../lib/energyModelV2/replayEngine.test";
import { runEnergyModelCoreUnitTests } from "../lib/energyModelV2/energyModelCore.test";
import { runHeatLossModelUnitTests } from "../lib/energyModelV2/heatLossModel.test";
import { runHeatLossChartUnitTests } from "../lib/energyModelV2/heatLossChart.test";
import { runReplayValidationUnitTests } from "../lib/energyModelV2/replayValidation.test";
import { runDashboardReplayUnitTests } from "../lib/energyModelV2/dashboardReplay.test";
import { runDashboardResourcesUnitTests } from "../lib/energyModelV2/dashboardResources.test";
import { runHomeResumeRefreshSourceTests } from "../tests/homeResumeRefreshSource.test";
import { runWaterDrawLabelUnitTests } from "../lib/energyModelV2/waterDrawLabels.test";
import { runWaterDrawLabelSnapshotMigrationTests } from "../tests/waterDrawLabelSnapshotMigration.test";

async function runTests() {
  runTankTemperatureForecastUnitTests();
  runInletTemperatureUnitTests();
  await runHeatingHistoryUnitTests();
  runHeatingEnergyCostUnitTests();
  runElectricityPricesUnitTests();
  runHistoryUiSourceTests();
  runHeatingGainHistorySourceTests();
  runHeatingPlanMarkerUnitTests();
  runElectricityPriceTrendUnitTests();
  runElectricityPriceFunctionUnitTests();
  runTemperatureHistoryDayUnitTests();
  runTemperatureHistoryRpcMigrationTests();
  runGetHeatingPeriodsRpcMigrationTests();
  runRecalculateTemperatureDropProfileRpcMigrationTests();
  await runSettingsDraftUnitTests();
  runSettingsScenarioUnitTests();
  runSettingsDraftUiSourceTests();
  runSettingsScenarioUiSourceTests();
  runHeatingOptimizerUnitTests();
  runHeatingOptimizationRunUnitTests();
  runHeatingOptimizationStatusSourceTests();
  await runHeatingGainUnitTests();
  runHeatingGainBacktestUnitTests();
  runHeatingRecoveryDropUnitTests();
  runRecoveryDropEnvironmentUnitTests();
  runHeatingPlanPresentationUnitTests();
  runHeatingPlanPublicationUnitTests();
  runHeatingSettingsUnitTests();
  runShowerReserveSettingsUnitTests();
  runSettingsSectionSummaryUnitTests();
  runTemperatureDropProfileUnitTests();
  runColorMixingUnitTests();
  runTemperatureColorsUnitTests();
  runTemperaturePresentationUnitTests();
  runPricePresentationUnitTests();
  runPriceUtilsUnitTests();
  runTankMonitorAlertUnitTests();
  runTankMonitorAlertLogicUnitTests();
  runInletTemperatureTrendUnitTests();
  runWaterDrawDetectionUnitTests();
  runTankReadingFreshnessUnitTests();
  runHomeResumeRefreshSourceTests();
  runSensorGeometryUnitTests();
  runReplayEngineUnitTests();
  runEnergyModelCoreUnitTests();
  runHeatLossModelUnitTests();
  runHeatLossChartUnitTests();
  runReplayValidationUnitTests();
  runDashboardReplayUnitTests();
  await runDashboardResourcesUnitTests();
  runWaterDrawLabelUnitTests();
  runWaterDrawLabelSnapshotMigrationTests();

  console.log(
    "tankTemperatureForecast, inletTemperature, heatingHistory, heatingEnergyCost, electricityPrices, electricityPriceTrend, electricityPriceFunction, temperatureHistoryDay, temperatureHistoryRpcMigration, getHeatingPeriodsRpcMigration, recalculateTemperatureDropProfileRpcMigration, settingsDraft, settingsScenario, settingsDraftUiSource, settingsScenarioUiSource, historyUiSource, heatingGainHistorySource, homeResumeRefreshSource, heatingPlanMarkers, heatingOptimizer, heatingOptimizationRun, heatingOptimizationStatusSource, heatingGain, heatingGainBacktest, heatingRecoveryDrop, recoveryDropEnvironment, heatingPlanPresentation, heatingPlanPublication, heatingSettings, settingsSectionSummaries, showerReserveSettings, temperatureDropProfile, colorMixing, temperatureColors, temperaturePresentation, pricePresentation, priceUtils, tankMonitorAlert, tankMonitorAlertLogic, inletTemperatureTrend, waterDrawDetection, tankReadingFreshness, sensorGeometry, replayEngine, energyModelCore, replayValidation, dashboardReplay and dashboardResources tests passed",
  );
}

void runTests();
